### ISSUE TITLE
Code 92 when booting with Ventoy

### ISSUE THREAD

**Issue by Sprunglesonthehub** [cobra3282000/AcreetionOS#10]
![error1-min](https://github.com/user-attachments/assets/477c87f0-051a-47f1-ba2f-0c3c2e618dc8)

Information Gathered: 
 - Ventoy version 1.0.99
 - Are using a UEFI
 - Latest version of AcreetionOS
 

Unsure about what is causing this. It seems like an incompatibility error? Let's look into this @cobra3282000

**Comment by cobra3282000** [comment]
this happens when using ventoy and there are onboard graphics and stuff.   there is a fix for it, but at grub menu for the OS you have to edit (E key) and add it to the cmd line stuff.   

This sounds like an issue with the display driver during boot. The "92" in the bottom right typically indicates that the system is still in the boot process but has encountered a graphics-related problem.
A few common solutions you could try:

Boot with kernel parameters by editing the boot entry in GRUB:

When the GRUB menu appears, press 'e'
Add one of these parameters to the line that starts with "linux":

nomodeset
nouveau.modeset=0 (if using NVIDIA)
video=SVIDEO-1:d (disables S-Video output)




If you're using an NVIDIA GPU, you might need to:

Boot in text mode first
Install proper NVIDIA drivers
Generate a new initramfs


Try disabling Secure Boot in your BIOS/UEFI settings if it's enabled

Which graphics card are you using? This information would help narrow down the specific solution you need.
